/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectuas.viewSwing;

/**
 *
 * @author user
 */
public class DashboardHome extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 180, 110, 0);

        jPanel2.setBackground(new java.awt.Color(239, 245, 245));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/ion_game-controller-outline.png"))); // NOI18N
        jLabel7.setText("GAMERY");
        jLabel7.setIconTextGap(8);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 30, 120, 30);

        jButton1.setBackground(new java.awt.Color(214, 228, 229));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/ri_home-5-line.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(6);
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 100, 170, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/eos-icons_admin-outlined.png"))); // NOI18N
        jButton2.setText("Manage Admin");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(6);
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 200, 170, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/teenyicons_game-controller-retro-outline.png"))); // NOI18N
        jButton3.setText("Manage Game");
        jButton3.setHideActionText(true);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setIconTextGap(6);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 150, 170, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/mdi_people-group-outline.png"))); // NOI18N
        jButton4.setText("Manage Customer");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setIconTextGap(6);
        jPanel2.add(jButton4);
        jButton4.setBounds(10, 250, 170, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/iconoir_playstation-gamepad_1.png"))); // NOI18N
        jButton5.setText("Manage Playstation");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setIconTextGap(6);
        jPanel2.add(jButton5);
        jButton5.setBounds(10, 300, 170, 40);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/simple-line-icons_logout.png"))); // NOI18N
        jButton6.setText("Logout");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setIconTextGap(8);
        jPanel2.add(jButton6);
        jButton6.setBounds(20, 570, 110, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 630);

        jPanel3.setBackground(new java.awt.Color(43, 52, 103));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Home Page");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(240, 10, 270, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("This application helps manage the needs of the Playstation rental business easily.");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(100, 50, 550, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("You can control anytime and anywhere through this application");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(150, 70, 430, 22);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 0, 730, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/image 11.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(780, 410, 120, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/The Legend of Zelda Poster Majora's Mask 1.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 410, 120, 180);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/image 9.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(410, 410, 120, 180);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/image 10.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(600, 410, 120, 180);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE_IMPORT/image 7.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(470, 120, 200, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 930, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
